# Usa la imagen oficial de SQL Server
FROM mcr.microsoft.com/mssql/server:2019-latest

# Variables de entorno (¡cambia la contraseña!)
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=HypernovaGaming2025!
ENV MSSQL_PID=Express
EXPOSE 1433